fix(loader): build the loader at installation
LesEchos/image-size-loader pull request #4
Opened 2021-07-12 15:47 UTC by EoleO

### Bug Fixes

- build the loader at installation

### Chores

- update `schema-utils`

2021-07-13 08:23 UTC, apascal approved these changes

2021-07-13 09:01 UTC, apascal reviewed
Rather build the distributed file on your side with a task explained in the readme to do it

2021-07-13 10:00 UTC, apascal requested changes

2021-07-13 10:00 UTC, apascal commented on .husky/pre-commit
> +npm run build & git add dist/
This is not linked to pre-commit, but rather prepublish, I would remove it all together as this is your responsibility to rebuild before pushing a new PR

2021-07-13 10:00 UTC, apascal commented on CHANGELOG.md
> +- precommit build the loader
unclear

2021-07-13 11:27 UTC, EoleO commented on .husky/pre-commit
> +npm run build & git add dist/
Done

2021-07-13 11:27 UTC, EoleO commented on CHANGELOG.md
> +- precommit build the loader
Done

2021-07-16 08:28 UTC, apascal approved these changes

2021-07-16 09:07 UTC, merged